apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-persistent-storage
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myssql-persistent-claim
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany

